# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 504115383abd056db8febc2f6cbf1e992f11c2f3b53abc65afe08c26f0bdc233a30386716ae5331122bafb82478df2dd4a173de8a2c45f258db1c0b3671a1e19

test:
  secret_key_base: 71f0b8e15ce3c101f97816348ee2e0e4fad50b90649b1688d1b38637163580cda015e5d6116125cf6bc04fe4434f35c51351e7dd9547cbffa9e4583818ad0b1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
